spring:
  application:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description"

  kafka:
    bootstrap-servers: localhost:29092
    topic-name: "topic-person-info"
    group-id: "service-person"
